# Generated by Django 3.2.5 on 2021-08-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentname',
            name='pollingunit_uniqueid',
            field=models.ForeignKey(db_column='pollingunit_uniqueid', on_delete=django.db.models.deletion.CASCADE, to='main.pollingunit'),
        ),
        migrations.AlterField(
            model_name='lga',
            name='state_id',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='main.states'),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='lga_id',
            field=models.ForeignKey(db_column='lga_id', on_delete=django.db.models.deletion.CASCADE, to='main.lga'),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniquewardid',
            field=models.ForeignKey(db_column='uniquewardid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='lga_id',
            field=models.ForeignKey(db_column='lga_id', on_delete=django.db.models.deletion.CASCADE, to='main.lga'),
        ),
    ]
