# Generated by Django 3.2.5 on 2021-08-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210819_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='lga_id',
            field=models.IntegerField(),
        ),
    ]
