# Generated by Django 3.2.5 on 2021-08-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pollingunit_lga_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='uniquewardid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
